LuizDubena/Controllers/SupplierController.cs
using Model.Registers;
using Services.Registers;
using System.Net;
using System.Web.Mvc;

namespace LuizDubena.Controllers
{
    public class SupplierController : Controller
    {
        private SupplierService supplierService = new SupplierService();

        #region [ Actions ]

        #region [ Index ]
        public ActionResult Index()
        {
            return View(supplierService.GetByName());
        }

        #endregion

        #region [ Create ]

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            return SaveSupplier(supplier);
        }

        #endregion

        #region [ Edit ]

        public ActionResult Edit(long? id)
        {
            return GetViewByID(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Supplier supplier)
        {
            return SaveSupplier(supplier);
        }

        #endregion

        #region [ Details ]

        public ActionResult Details(long? id)
        {
            return GetViewByID(id);        
        }
        #endregion

        #region [ Delete ]

        public ActionResult Delete(long? id)
        {
            return GetViewByID(id);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            try
            {
                Supplier supplier = supplierService.DeleteByID(id);
                TempData["Message"] = "Supplier " + supplier.Name.ToUpper() + "	was removed";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        #endregion

        #endregion

        private ActionResult GetViewByID(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplier supplier = supplierService.GetByID((long)id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }        private ActionResult SaveSupplier(Supplier supplier)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    supplierService.Save(supplier);
                    return RedirectToAction("Index");
                }
                return View(supplier);
            }
            catch
            {
                return View(supplier);
            }
        }
    }
}

LuizDubena/Views/Supplier/Create.cshtml
@model Model.Registers.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Suppliers Create";
}

@using (Html.BeginForm())
{				
    @Html.AntiForgeryToken()
    <div class="panel	panel-primary">
        <div class="panel-heading">	 
        Registering a new Supplier	
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                 @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                 <div class="from-group">
                     @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                     <div class="col-md-10">
                         @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                         @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                     </div>
                 </div>
            </div>
         </div>
         <div class="panel-footer panel-info">
             <div class="col-md-offset-2 col-md-10">
                 <input type="submit"
                        value="Add Supplier"
                        class="btn btn-danger" />
                 @Html.ActionLink("Return to Supplier List", "Index", null, new { @class = "btn btn-warning" })
             </div>
             <br />
             <br />
         </div>
      </div>
}

@section ScriptPage {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

LuizDubena/Views/Supplier/Delete.cshtml
@model Model.Registers.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Suppliers Delete";
}

<div class="panel	panel-primary">				
    <div class="panel-heading">								
    Supplier Data				
    </div>				
    <div class="panel-body">								
        <div class="form-group">												
            @Html.LabelFor(model => model.Name)
        <br />												
            <div class="input-group">																
                <span class="input-group-addon">																				
                <i class="glyphicon	glyphicon-user"></i>																
                </span>																
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })												
            </div>								
        </div>				
    </div>				
    <div class="panel-footer	panel-info">
        <a href="#" class="btn	btn-info" data-toggle="modal" data-target="#deleteConfirmationModal">Remove</a>
        @Html.ActionLink("Return to Index", "Index", null, new { @class = "btn	btn-info" })
    </div>
</div>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-ELTEismiss="modal" aria-hidden="true">	&times;	</button>
                <h4 class="modal-title"> Supplier Delete Confirmation </h4>
            </div>
            <div class="modal-body">
                <p>	You are about to remove the Supplier @Model.Name.ToUpper() . </p>
                <p>
                    <strong>
                        Are you sure you want to proced?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Supplier", FormMethod.Post, new { @id = "delete-form", role = "form" }))
                {
                    @Html.HiddenFor(m => m.SupplierID)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn	btn-default" onclick="$('#delete-form').submit();">	Yes, delete it.	</button>
                <button type="button" class="btn	btn-primary" data-dismiss="modal"> No, don't delete it.	</button>
            </div>
        </div>
    </div>
</div>

@Html.Partial("~/Views/Products/_ForSupplier.cshtml", Model.Products.ToList())

LuizDubena/Views/Supplier/Details.cshtml
@model Model.Registers.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Suppliers Details";
}

<div class="panel	panel-primary">				
    <div class="panel-heading">								
        Supplier Details				
    </div>				
    <div class="panel-body">												
        <div class="form-group">																
            @Html.LabelFor(model => model.Name)																
        <br />																
        <div class="input-group">																				
            <span class="input-group-addon">																								
            <i class="glyphicon	glyphicon-user"></i>																				
            </span>																				
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })																
            </div>												
        </div>				
    </div>				
    <div class="panel-footer	panel-info">								
        @Html.ActionLink("Edit", "Edit", new { id = Model.SupplierID }, new { @class = "btn	btn-info" })								
        @Html.ActionLink("Return to Index", "Index", null, new { @class = "btn	btn-info" })				
    </div> 
</div>
@Html.Partial("~/Views/Products/_ForSupplier.cshtml", Model.Products.ToList())

LuizDubena/Views/Supplier/Edit.cshtml
@model Model.Registers.Supplier

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Suppliers Edit";
}

@using (Html.BeginForm())
{				@Html.AntiForgeryToken()
    <div class="panel	panel-primary">
        <div class="panel-heading"> Alteração dos dados	de um FABRICANTE</div>								
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.SupplierID)
                <div class="form-group">
                     @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label	col-md-2" })
                     <div class="col-md-10">																								
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })																				
                    </div>																
                </div>
            </div>												
            <div class="panel-footer	panel-info">
               <div class="col-md-offset-2	col-md-10">
                    <input type="submit" value="Gravar	alterações" class="btn	btn-info" />
                        @Html.ActionLink("Return to Index","Index", null, new{ @class = "btn btn-warning" })
               </div>																
                <br />																
               <br />
            </div>
        </div>
    </div> 
}
@Html.Partial("~/Views/Products/_ForSupplier.cshtml", Model.Products.ToList())
@section	ScriptPage	{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script> 
}

LuizDubena/Views/Supplier/Index.cshtml
@model IEnumerable<Model.Registers.Supplier>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Suppliers List";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Registered Supplier
    </div>
    <div class="panel-body">
        <table class="table	table-striped	table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.SupplierID })	|
                            @Html.ActionLink("Details", "Details", new { id = item.SupplierID })	|
                            @Html.ActionLink("Delete", "Delete", new { id = item.SupplierID })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        66 3.3	ADAPTING VIEWS TO USE BOOTSTRAP
        @Html.ActionLink("Register a new Supplier","Create", null, new
        {
          @class ="btn	btn-success"
        })
    </div>
</div>
    <tr>
        @Html.ActionLink("Delete Range", "DeleteRange")
    </tr>
@section styles{
    <link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")"	rel="stylesheet"/>
}
@section ScriptPage	{
<script src=" @Url.Content("~/Scripts/DataTables/jquery.dataTables.js") "></script>
<script src="@Url.Content("~/Scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.table').dataTable();
        });
    </script>
}